### ISSUE TITLE
What is the rc_Conv1D block about?

### ISSUE THREAD

**Issue by vuhongai** [1edv/evolution#7]
Hi,
Thank you for sharing your awesome work.
I have difficulty to understand the intuition of the use of rc_Conv1D block in the attention-based model, since it is new for me. If I understand correctly, you're trying to mimic the DNA structure with forward and reverse stand, right? I have tried with a dataset of protein sequence (just modify the function to generate onehot vector) to function, and the architecture works also very well (figure: validative set of the training). 
![image](https://user-images.githubusercontent.com/40607965/183687312-5569ef8a-ba88-4602-a0c6-b147b5f69781.png)

So my question is, what exactly this rc_Conv1D block does in other case rather than DNA sequence?
Thank you.
Ai

**Comment by Carldeboer** [comment]
Hi Ai

The idea of that function is to incorporate the reverse complement DNA strand since the strand is arbitrary and transcription factors bind in either orientation. It is more efficient for a variety of reasons to reverse complement the convolutional filters rather than the input DNA sequences. So that layer uses reverse complemented filters to do a 1D convolution. The reverse complement actually works by flipping the filters along the length and base axes (and the bases have to be in a specific order so that the flip actually represents complementation; so ACGT works since TGCA is its complement, but ATGC does not since CGTA is not the complement of ATGC). 

Are your protein sequences a one hot encoding of amino acids? e.g. 20xL (L=length; 20 - one per amino acid)

If so, I cannot explain why the rc_Conv1D would help as it really doesn't make sense for that application. There is no logical meaning to a reverse complement of a protein sequence. Have you tried the same model, but without the rc_Conv1d? If not, perhaps it is the rest of the model that is helping.

**Comment by vuhongai** [comment]
Thank you for your considerate response. 
And yes you're right, if I replace with normal Conv1D, it works as well. Anyway, thank you for sharing the architecture, it learns very robustly.

Ai

**Comment by 1edv** [comment]
Thanks so much for your question @vuhongai ! I am just adding a couple points to @Carldeboer's excellent answer:

- For the regulatory sequence->function model in the paper, the rc_Conv1d block was originally introduced because it was often present in prior work on related problems.  '[Towards a Better Understanding of Reverse-Complement Equivariance for Deep Learning Models in Regulatory Genomics](https://www.biorxiv.org/content/10.1101/2020.11.04.368803v2)' does a great job of conveying the intuition behind why one may want to employ such reverse-complement aware models and thoroughly benchmarking various existing strategies (This [twitter thread](https://twitter.com/anshulkundaje/status/1324358714644525056?s=20&t=dh5uMgjzzJUkx6vgMYr-9w) summarizes ) 

- It is great to hear that the model architecture learns protein sequence->function robustly! I agree with @Carldeboer's suggestion that it is likely the rest of the model that is helping. (If there are more details available for the protein->sequence function task, like the function label (eg: GFP expression) and length of input protein sequence (eg: ~238 AAs), we can try to think more deeply about why the architecture is able to learn robustly for your specific application.
['Learning protein fitness models from evolutionary and assay-labeled data' ](https://www.nature.com/articles/s41587-021-01146-5) wonderfully demonstrates how simple linear regression models on site-specific amino acid features often perform quite well at protein sequence->function task. Quoting a paragraph I liked from their discussion:
> One may initially be puzzled as to how linear models with only site-specific features can generalize at all to mutations not seen at train time, let alone surpass nonlinear models in this task. However, as detailed in the [Methods](https://www.nature.com/articles/s41587-021-01146-5#Sec12), such generalization can emerge from a particular form of l2-regularized linear regression with one-hot encoded features. In effect, through the regularization, the model learns about the importance of each position, even though each amino acid at each position has its own parameter. Thus, if the effects of different mutations at the same position are in the same direction, the regularized linear models can do a reasonable job of generalizing in such a manner.  
I found this paper as a great starting point for building intuition on the protein sequence->function task.

Best,
Eeshit

**Comment by vuhongai** [comment]
Thank you for your clarification and the suggestions. I will look into it.
Bests,
Ai
