### ISSUE TITLE
Scaler Transform for the Targets

### ISSUE THREAD

**Issue by aga-relation** [1edv/evolution#9]
Hi, in your [code](https://github.com/1edv/evolution/blob/master/manuscript_code/model/tpu_model/train_model.ipynb) you seem to be scaling the target values before training, however I am struggling to find reference to this procedure in the manuscript?
The only mention of scaling I can find appears to be for purely visualisation purposes (section titled **Visualizing promoter fitness landscapes**). Would you mind pointing me to where I can find more detail about the procedure and to how the scaler was trained? 

Thank you!

**Comment by 1edv** [comment]
Hi,

The _**"Generate standard scaler for positive and negative selection experiments using the extreme cases of the designed sequences (Done together since designed sequences are from the same file )"**_ section in the https://github.com/1edv/evolution/blob/master/manuscript_code/model/tpu_model/data_processing.ipynb fjle describes how the scaler was trained.

(Also, the scaler isn't strictly necessary here - you should be able to get equivalent results even without the scaler.

Best,
Eeshit
